import type { Skill, Tool } from './types';
import { CodeIcon } from './components/icons/CodeIcon';
import { DesignIcon } from './components/icons/DesignIcon';
import { VideoIcon } from './components/icons/VideoIcon';
import { WriteIcon } from './components/icons/WriteIcon';
import { MarketingIcon } from './components/icons/MarketingIcon';
import { AnimationIcon } from './components/icons/AnimationIcon';
import { AnalyzeIcon } from './components/icons/AnalyzeIcon';
import { MovieIcon } from './components/icons/MovieIcon';
import { ChatIcon } from './components/icons/ChatIcon';
import { ImageIcon } from './components/icons/ImageIcon';
import { BoltIcon } from './components/icons/BoltIcon';
import { DownloadIcon } from './components/icons/DownloadIcon';
import { AudioIcon } from './components/icons/AudioIcon';

export const SKILLS: Skill[] = [
  {
    id: 'graphic-design',
    name: 'Graphic Design',
    description: 'Shaandaar visuals aur illustrations banana seekhein.',
    icon: DesignIcon,
    color: 'from-pink-500 to-rose-500',
    type: 'skill',
    path: '/category/graphic-design',
  },
  {
    id: 'video-editing',
    name: 'Video Editing',
    description: 'Video ke zariye kahani sunane ki kala mein maahir banein.',
    icon: VideoIcon,
    color: 'from-blue-500 to-cyan-500',
    type: 'skill',
    path: '/category/video-editing',
  },
  {
    id: 'content-writing',
    name: 'Content Writing',
    description: 'Zabardast kahaniyan aur asardaar copy likhna seekhein.',
    icon: WriteIcon,
    color: 'from-green-400 to-emerald-500',
    type: 'skill',
    path: '/category/content-writing',
  },
  {
    id: 'programming',
    name: 'Programming',
    description: 'Websites, apps, aur software solutions banana seekhein.',
    icon: CodeIcon,
    color: 'from-indigo-500 to-purple-600',
    type: 'skill',
    path: '/category/programming',
  },
  {
    id: 'digital-marketing',
    name: 'Digital Marketing',
    description: 'Brands aur audience ko online badhayein.',
    icon: MarketingIcon,
    color: 'from-amber-500 to-orange-500',
    type: 'skill',
    path: '/category/digital-marketing',
  },
  {
    id: 'animation',
    name: 'Animation',
    description: 'Motion graphics se ideas ko zinda karein.',
    icon: AnimationIcon,
    color: 'from-teal-400 to-sky-500',
    type: 'skill',
    path: '/category/animation',
  },
];

export const TOOLS: Tool[] = [
  {
    id: 'qna-bot',
    name: 'AI Dost',
    description: 'Google Search se jude, up-to-date jawabat paayein.',
    icon: ChatIcon,
    color: 'from-cyan-500 to-blue-500',
    type: 'tool',
    path: '/qna-bot',
  },
  {
    id: 'image-generator',
    name: 'Chitra-AI',
    description: 'Apne ideas ko 4K quality tak ki images mein badlein.',
    icon: ImageIcon,
    color: 'from-rose-400 to-red-500',
    type: 'tool',
    path: '/image-generator',
  },
  {
    id: 'rocket-writer',
    name: 'Rocket Writer',
    description: 'Bijli ki tezi se content ideas aur headlines paayein.',
    icon: BoltIcon,
    color: 'from-amber-400 to-orange-500',
    type: 'tool',
    path: '/rocket-writer',
  },
  {
    id: 'image-analyzer',
    name: 'Chitra Reporter',
    description: 'Photo upload karein aur uske baare mein kuch bhi poochein.',
    icon: AnalyzeIcon,
    color: 'from-red-500 to-orange-500',
    type: 'tool',
    path: '/image-analyzer',
  },
  {
    id: 'video-analyzer',
    name: 'Video Ka Jasoos',
    description: 'Video upload karein aur uske andar ki jaankari nikalein.',
    icon: VideoIcon,
    color: 'from-purple-500 to-indigo-500',
    type: 'tool',
    path: '/video-analyzer',
  },
  {
    id: 'image-animator',
    name: 'Photo Ko Jivdan Do',
    description: 'Ek photo se Veo ki madad se video banayein.',
    icon: MovieIcon,
    color: 'from-green-500 to-teal-500',
    type: 'tool',
    path: '/image-animator',
  },
  {
    id: 'media-downloader',
    name: 'Media Downloader',
    description: 'Direct media links se image/video/audio download karein.',
    icon: DownloadIcon,
    color: 'from-slate-500 to-zinc-600',
    type: 'tool',
    path: '/media-downloader',
  },
  {
    id: 'resume-cover-letter',
    name: 'Resume + Cover Letter AI',
    description: 'ATS-friendly resume aur cover letter generate karein.',
    icon: WriteIcon,
    color: 'from-blue-500 to-indigo-600',
    type: 'tool',
    path: '/tools/resume-cover-letter',
  },
  {
    id: 'proposal-writer',
    name: 'Proposal Writer',
    description: 'Winning client proposals turant taiyar karein.',
    icon: MarketingIcon,
    color: 'from-amber-500 to-orange-500',
    type: 'tool',
    path: '/tools/proposal-writer',
  },
  {
    id: 'invoice-quotation',
    name: 'Invoice + Quotation',
    description: 'Professional invoice aur quotation generate karein.',
    icon: DownloadIcon,
    color: 'from-emerald-500 to-green-600',
    type: 'tool',
    path: '/tools/invoice-quotation',
  },
  {
    id: 'contract-generator',
    name: 'Contract Generator',
    description: 'Freelance agreement draft ready karein.',
    icon: CodeIcon,
    color: 'from-slate-500 to-gray-700',
    type: 'tool',
    path: '/tools/contract-generator',
  },
  {
    id: 'portfolio-builder',
    name: 'Portfolio Builder',
    description: 'Case-study based portfolio content banayein.',
    icon: DesignIcon,
    color: 'from-pink-500 to-rose-600',
    type: 'tool',
    path: '/tools/portfolio-builder',
  },
  {
    id: 'thumbnail-hook-generator',
    name: 'Thumbnail + Hook',
    description: 'High-CTR hooks aur thumbnail text ideas paayein.',
    icon: VideoIcon,
    color: 'from-red-500 to-pink-600',
    type: 'tool',
    path: '/tools/thumbnail-hook-generator',
  },
  {
    id: 'seo-blog-toolkit',
    name: 'SEO Blog Toolkit',
    description: 'Keywords, outline, meta tags aur FAQ schema banayein.',
    icon: AnalyzeIcon,
    color: 'from-cyan-500 to-sky-600',
    type: 'tool',
    path: '/tools/seo-blog-toolkit',
  },
  {
    id: 'social-calendar',
    name: 'Social Calendar',
    description: '30-day social content plan generate karein.',
    icon: ChatIcon,
    color: 'from-violet-500 to-purple-600',
    type: 'tool',
    path: '/tools/social-calendar',
  },
  {
    id: 'meeting-action-items',
    name: 'Meeting Action Items',
    description: 'Meeting notes ko tasks aur deadlines me badlein.',
    icon: AudioIcon,
    color: 'from-teal-500 to-cyan-600',
    type: 'tool',
    path: '/tools/meeting-action-items',
  },
  {
    id: 'email-assistant',
    name: 'Email Assistant',
    description: 'Client emails aur follow-ups smartly draft karein.',
    icon: WriteIcon,
    color: 'from-indigo-500 to-blue-600',
    type: 'tool',
    path: '/tools/email-assistant',
  },
  {
    id: 'pricing-calculator',
    name: 'Pricing Calculator',
    description: 'Hourly aur package rates calculate karein.',
    icon: BoltIcon,
    color: 'from-yellow-500 to-amber-600',
    type: 'tool',
    path: '/tools/pricing-calculator',
  },
  {
    id: 'file-converter',
    name: 'File Converter',
    description: 'Image files ko PNG/JPG/WEBP me convert karein.',
    icon: ImageIcon,
    color: 'from-green-500 to-lime-600',
    type: 'tool',
    path: '/tools/file-converter',
  },
  {
    id: 'code-bug-finder',
    name: 'Code Bug Finder',
    description: 'Code bugs detect karke refactor suggestions paayein.',
    icon: CodeIcon,
    color: 'from-purple-500 to-indigo-700',
    type: 'tool',
    path: '/tools/code-bug-finder',
  },
  {
    id: 'interview-prep-bot',
    name: 'Interview Prep Bot',
    description: 'Role-based mock interview aur prep plan paayein.',
    icon: ChatIcon,
    color: 'from-fuchsia-500 to-pink-600',
    type: 'tool',
    path: '/tools/interview-prep-bot',
  },
  {
    id: 'habit-sprint-tracker',
    name: 'Habit Sprint Tracker',
    description: 'Daily tasks track karke productivity boost karein.',
    icon: BoltIcon,
    color: 'from-orange-500 to-red-600',
    type: 'tool',
    path: '/tools/habit-sprint-tracker',
  },
];

export const MAKER_PROFILE = {
  name: 'Editor Nishant',
  role: 'Video Editor + Developer',
  bio: 'Main is website ka maker hoon. Mera focus creative learning experiences, smooth UI animations, aur practical skill growth systems banana hai.',
  email: 'arvind90782@gmail.com',
  website: 'https://skillskahub.vercel.app',
  instagram: 'https://instagram.com/editor.nishant',
};

export const WEBSITE_FAQ = [
  {
    q: 'Ye website kis ke liye hai?',
    a: 'Beginners aur freelancers dono ke liye. Yahan structured courses, AI tools, practice flow aur real output system diya gaya hai.',
  },
  {
    q: 'Kya courses full practical hain?',
    a: 'Haan. Har course me step-by-step flow, quick checks, quizzes, activity board aur reward unlock system diya gaya hai.',
  },
  {
    q: 'Special member kaise bante hain?',
    a: 'Course end tak complete karke last page par special member claim karo. Fir assets pack aur member perks unlock ho jate hain.',
  },
  {
    q: 'Agar app slow lage ya error aaye to?',
    a: 'Reload karo aur dobara try karo. Agar issue rahe to maker section me diye contact pe details share karo.',
  },
];
