import type { Skill, Tool } from './types';
import { CodeIcon } from './components/icons/CodeIcon';
import { DesignIcon } from './components/icons/DesignIcon';
import { VideoIcon } from './components/icons/VideoIcon';
import { WriteIcon } from './components/icons/WriteIcon';
import { MarketingIcon } from './components/icons/MarketingIcon';
import { AnimationIcon } from './components/icons/AnimationIcon';
import { AnalyzeIcon } from './components/icons/AnalyzeIcon';
import { MovieIcon } from './components/icons/MovieIcon';
import { ChatIcon } from './components/icons/ChatIcon';
import { ImageIcon } from './components/icons/ImageIcon';
import { BoltIcon } from './components/icons/BoltIcon';
import { DownloadIcon } from './components/icons/DownloadIcon';
import { AudioIcon } from './components/icons/AudioIcon';

export const SKILLS: Skill[] = [
  {
    id: 'graphic-design',
    name: 'Graphic Design',
    description: 'Learn how to create polished visuals, brand assets, and illustrations.',
    icon: DesignIcon,
    color: 'from-pink-500 to-rose-500',
    type: 'skill',
    path: '/category/graphic-design',
  },
  {
    id: 'video-editing',
    name: 'Video Editing',
    description: 'Turn raw footage into stories that feel sharp, clear, and engaging.',
    icon: VideoIcon,
    color: 'from-blue-500 to-cyan-500',
    type: 'skill',
    path: '/category/video-editing',
  },
  {
    id: 'content-writing',
    name: 'Content Writing',
    description: 'Write clear copy, strong narratives, and content that keeps attention.',
    icon: WriteIcon,
    color: 'from-green-400 to-emerald-500',
    type: 'skill',
    path: '/category/content-writing',
  },
  {
    id: 'programming',
    name: 'Programming',
    description: 'Build websites, apps, and software solutions with confidence.',
    icon: CodeIcon,
    color: 'from-indigo-500 to-purple-600',
    type: 'skill',
    path: '/category/programming',
  },
  {
    id: 'digital-marketing',
    name: 'Digital Marketing',
    description: 'Grow brands and audiences with practical online marketing skills.',
    icon: MarketingIcon,
    color: 'from-amber-500 to-orange-500',
    type: 'skill',
    path: '/category/digital-marketing',
  },
  {
    id: 'animation',
    name: 'Animation',
    description: 'Bring ideas to life with motion, timing, and visual rhythm.',
    icon: AnimationIcon,
    color: 'from-teal-400 to-sky-500',
    type: 'skill',
    path: '/category/animation',
  },
];

export const TOOLS: Tool[] = [
  {
    id: 'secret-creator-lab',
    name: 'Secret Creator Lab',
    description: 'Unlock premium creator tools and reward content by completing courses.',
    icon: BoltIcon,
    color: 'from-fuchsia-500 to-cyan-500',
    type: 'tool',
    path: '/secret-creator-lab',
  },
  {
    id: 'ultra-tools',
    name: 'Ultra Tools',
    description: 'Advanced AI brainstorming tools for creators, editors, and strategists.',
    icon: BoltIcon,
    color: 'from-purple-500 to-pink-500',
    type: 'tool',
    path: '/ultra-tools',
  },
  {
    id: 'qna-bot',
    name: 'AI Buddy',
    description: 'Ask questions and get fresh answers with search-backed AI.',
    icon: ChatIcon,
    color: 'from-cyan-500 to-blue-500',
    type: 'tool',
    path: '/qna-bot',
  },
  {
    id: 'image-generator',
    name: 'Image AI',
    description: 'Turn text prompts into stunning images.',
    icon: ImageIcon,
    color: 'from-rose-400 to-red-500',
    type: 'tool',
    path: '/image-generator',
  },
  {
    id: 'rocket-writer',
    name: 'Rocket Writer',
    description: 'Generate fast, clean copy for ideas, captions, and prompts.',
    icon: WriteIcon,
    color: 'from-amber-400 to-orange-500',
    type: 'tool',
    path: '/rocket-writer',
  },
  {
    id: 'image-analyzer',
    name: 'Image Reporter',
    description: 'Upload an image and ask the AI what it notices.',
    icon: AnalyzeIcon,
    color: 'from-red-500 to-orange-500',
    type: 'tool',
    path: '/image-analyzer',
  },
  {
    id: 'video-analyzer',
    name: 'Video Detective',
    description: 'Upload a video and pull useful insights from it.',
    icon: VideoIcon,
    color: 'from-purple-500 to-indigo-500',
    type: 'tool',
    path: '/video-analyzer',
  },
  {
    id: 'image-animator',
    name: 'Animate Photo',
    description: 'Turn a single image into a short animated video.',
    icon: MovieIcon,
    color: 'from-green-500 to-teal-500',
    type: 'tool',
    path: '/image-animator',
  },
  {
    id: 'media-downloader',
    name: 'Media Downloader',
    description: 'Download direct image, video, or audio links safely.',
    icon: DownloadIcon,
    color: 'from-slate-500 to-zinc-600',
    type: 'tool',
    path: '/media-downloader',
  },
  {
    id: 'resume-cover-letter',
    name: 'Resume + Cover Letter AI',
    description: 'Generate ATS-friendly resumes and cover letters.',
    icon: WriteIcon,
    color: 'from-blue-500 to-indigo-600',
    type: 'tool',
    path: '/tools/resume-cover-letter',
  },
  {
    id: 'proposal-writer',
    name: 'Proposal Writer',
    description: 'Draft stronger client proposals in seconds.',
    icon: MarketingIcon,
    color: 'from-amber-500 to-orange-500',
    type: 'tool',
    path: '/tools/proposal-writer',
  },
  {
    id: 'invoice-quotation',
    name: 'Invoice + Quotation',
    description: 'Create professional invoices and quotations quickly.',
    icon: DownloadIcon,
    color: 'from-emerald-500 to-green-600',
    type: 'tool',
    path: '/tools/invoice-quotation',
  },
  {
    id: 'contract-generator',
    name: 'Contract Generator',
    description: 'Create a clean freelance agreement draft.',
    icon: CodeIcon,
    color: 'from-slate-500 to-gray-700',
    type: 'tool',
    path: '/tools/contract-generator',
  },
  {
    id: 'portfolio-builder',
    name: 'Portfolio Builder',
    description: 'Turn projects into polished case-study content.',
    icon: DesignIcon,
    color: 'from-pink-500 to-rose-600',
    type: 'tool',
    path: '/tools/portfolio-builder',
  },
  {
    id: 'thumbnail-hook-generator',
    name: 'Thumbnail + Hook',
    description: 'Get high-CTR hook ideas and thumbnail text variations.',
    icon: VideoIcon,
    color: 'from-red-500 to-pink-600',
    type: 'tool',
    path: '/tools/thumbnail-hook-generator',
  },
  {
    id: 'seo-blog-toolkit',
    name: 'SEO Blog Toolkit',
    description: 'Generate keywords, outlines, meta tags, and FAQs.',
    icon: AnalyzeIcon,
    color: 'from-cyan-500 to-sky-600',
    type: 'tool',
    path: '/tools/seo-blog-toolkit',
  },
  {
    id: 'social-calendar',
    name: 'Social Calendar',
    description: 'Build a 30-day social content plan.',
    icon: ChatIcon,
    color: 'from-violet-500 to-purple-600',
    type: 'tool',
    path: '/tools/social-calendar',
  },
  {
    id: 'meeting-action-items',
    name: 'Meeting Action Items',
    description: 'Convert meeting notes into tasks and deadlines.',
    icon: AudioIcon,
    color: 'from-teal-500 to-cyan-600',
    type: 'tool',
    path: '/tools/meeting-action-items',
  },
  {
    id: 'email-assistant',
    name: 'Email Assistant',
    description: 'Draft better client emails and follow-ups.',
    icon: WriteIcon,
    color: 'from-indigo-500 to-blue-600',
    type: 'tool',
    path: '/tools/email-assistant',
  },
  {
    id: 'pricing-calculator',
    name: 'Pricing Calculator',
    description: 'Estimate hourly rates and package pricing.',
    icon: BoltIcon,
    color: 'from-yellow-500 to-amber-600',
    type: 'tool',
    path: '/tools/pricing-calculator',
  },
  {
    id: 'file-converter',
    name: 'File Converter',
    description: 'Convert image files between PNG, JPG, and WEBP.',
    icon: ImageIcon,
    color: 'from-green-500 to-lime-600',
    type: 'tool',
    path: '/tools/file-converter',
  },
  {
    id: 'code-bug-finder',
    name: 'Code Bug Finder',
    description: 'Spot bugs and get cleaner refactor suggestions.',
    icon: CodeIcon,
    color: 'from-purple-500 to-indigo-700',
    type: 'tool',
    path: '/tools/code-bug-finder',
  },
  {
    id: 'interview-prep-bot',
    name: 'Interview Prep Bot',
    description: 'Practice role-based mock interviews and prep plans.',
    icon: ChatIcon,
    color: 'from-fuchsia-500 to-pink-600',
    type: 'tool',
    path: '/tools/interview-prep-bot',
  },
  {
    id: 'habit-sprint-tracker',
    name: 'Habit Sprint Tracker',
    description: 'Track daily tasks and keep your momentum visible.',
    icon: BoltIcon,
    color: 'from-orange-500 to-red-600',
    type: 'tool',
    path: '/tools/habit-sprint-tracker',
  },
  {
    id: 'smart-link-hub',
    name: 'Smart Link Hub',
    description: 'Turn raw links into structured knowledge and action systems.',
    icon: AnalyzeIcon,
    color: 'from-emerald-500 to-teal-500',
    type: 'tool',
    path: '/smart-link-hub',
  },
];

export const MAKER_PROFILE = {
  name: 'Nishant Singh',
  role: 'Video Editor, Website Developer, and Creative Designer',
  bio: 'I am a creative student and digital creator who enjoys building products where technology and creativity meet. I love video editing and I enjoy exploring tools that help ideas become real.',
  story:
    'I built this website so people can learn skills through fun, interactive, and practical experiences instead of boring courses. The goal is to help learners move faster and smarter.',
  email: 'arvind90782@gmail.com',
  website: 'https://skillskahub.vercel.app',
  instagram: 'https://instagram.com/editor.nishant',
  imageUrl: 'https://drive.google.com/uc?export=download&id=1e_jpmmyBMp9GT7aKE3_mFVQ5amBxhCZ-',
  skills: ['Video Editing', 'Thumbnail Design', 'Graphic Design', 'Website Development', 'AI Tools Building', 'Content Creation'],
  services: [
    { title: 'Video Editor', description: 'Professional editing for YouTube, Instagram, and more' },
    { title: 'Website Developer', description: 'Modern, fast, and polished websites' },
    { title: 'Creative Designer', description: 'Thumbnails, graphics, and visual content' },
  ],
};

export const WEBSITE_FAQ = [
  {
    q: 'Who is this website for?',
    a: 'It is designed for beginners and freelancers who want a practical, interactive way to learn skills.',
  },
  {
    q: 'Are the courses practical?',
    a: 'Yes. Each course uses step-by-step lessons, quick checks, quizzes, activity boards, and rewards.',
  },
  {
    q: 'How do I become a special member?',
    a: 'Complete the full course and claim the special member reward on the final page.',
  },
  {
    q: 'What should I do if the app feels slow or shows an error?',
    a: 'Refresh the page and try again. If the issue continues, contact the creator with the details.',
  },
];
